-- Migration 032: Note de Culegere (ERP Picking Notes)
-- Purpose: Store picking/cutting notes generated by ERP (e.g. CMD_116731)
--          These drive the warehouse picking workflow for cable orders.

-- ============================================================
-- Main pick_notes table
-- ============================================================
CREATE TABLE IF NOT EXISTS pick_notes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    erp_cmd_number    VARCHAR(50) UNIQUE NOT NULL,        -- CMD_116731
    erp_date          DATE,
    partner_name      VARCHAR(200),                        -- CER ELECTRO AVG S.R.L.
    contact_person    VARCHAR(150),                        -- CROITORU GEO
    agent_name        VARCHAR(150),                        -- DOBRESCU DANIEL
    delivery_type     VARCHAR(200),                        -- TRANSPORT NK SMART CABLES
    total_weight      NUMERIC(12, 2),                      -- 331.40 kg
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                          CHECK (status IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
    source            VARCHAR(20) NOT NULL DEFAULT 'MANUAL_UPLOAD'
                          CHECK (source IN ('ERP_AUTO','ERP_WEBHOOK','MANUAL_UPLOAD')),
    picking_job_id    UUID,                                -- FK added after picking_jobs exists
    notes             TEXT,
    erp_raw           JSONB,                               -- raw payload from ERP (audit)
    created_by        VARCHAR(100),
    created_at        TIMESTAMP DEFAULT NOW(),
    updated_at        TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Lines table
-- ============================================================
CREATE TABLE IF NOT EXISTS pick_note_lines (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pick_note_id        UUID NOT NULL REFERENCES pick_notes(id) ON DELETE CASCADE,
    line_number         INTEGER NOT NULL DEFAULT 1,
    product_name        VARCHAR(300),                      -- CYY-F 5X2.5 NYY-FR
    stock_code          VARCHAR(100),                      -- VZCB_CMP (Cod gest.)
    length_available    NUMERIC(14, 4),                    -- 0.812 km (lungime din care se taie)
    quantity_to_pick    NUMERIC(14, 4) NOT NULL,           -- 0.500 km (cantitate de)
    uom                 VARCHAR(20) DEFAULT 'Km',          -- Km / buc / m
    lot_number          VARCHAR(300),                      -- ##E1000 POWERVINE 0-1012 1012 M
    quantity_remaining  NUMERIC(14, 4),                    -- 0.312 km (cantitate ramasa)
    weight              NUMERIC(12, 2),                    -- 147.50 kg
    requested_lengths   TEXT,                              -- Lungimi solicitate (free text)
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING','IN_PROGRESS','DONE','CANCELLED')),
    picking_item_id     UUID,                              -- linked picking job item
    created_at          TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_pick_notes_status        ON pick_notes(status);
CREATE INDEX IF NOT EXISTS idx_pick_notes_erp_cmd       ON pick_notes(erp_cmd_number);
CREATE INDEX IF NOT EXISTS idx_pick_notes_erp_date      ON pick_notes(erp_date DESC);
CREATE INDEX IF NOT EXISTS idx_pick_notes_partner       ON pick_notes(partner_name);
CREATE INDEX IF NOT EXISTS idx_pick_notes_created       ON pick_notes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pick_note_lines_note     ON pick_note_lines(pick_note_id);
CREATE INDEX IF NOT EXISTS idx_pick_note_lines_status   ON pick_note_lines(status);
CREATE INDEX IF NOT EXISTS idx_pick_note_lines_lot      ON pick_note_lines(lot_number);

-- ============================================================
-- Auto-update updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION update_pick_notes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pick_notes_updated_at
    BEFORE UPDATE ON pick_notes
    FOR EACH ROW
    EXECUTE FUNCTION update_pick_notes_updated_at();

-- ============================================================
-- Comments
-- ============================================================
COMMENT ON TABLE pick_notes IS 'Note de culegere generate de ERP — documente ce declansează fluxul de picking cabluri in depozit';
COMMENT ON COLUMN pick_notes.erp_cmd_number IS 'Numarul comenzii din ERP (ex: CMD_116731)';
COMMENT ON COLUMN pick_notes.source IS 'Sursa importului: ERP_AUTO=webhook automat, ERP_WEBHOOK=push de la ERP, MANUAL_UPLOAD=incarcare manuala JSON';
COMMENT ON COLUMN pick_notes.erp_raw IS 'Payload JSON brut primit de la ERP (pentru audit)';
COMMENT ON COLUMN pick_note_lines.length_available IS 'Lungimea totala din care se taie (km) — lungimea rola/toba disponibila';
COMMENT ON COLUMN pick_note_lines.quantity_to_pick IS 'Cantitatea solicitata de client (km/buc/m)';
COMMENT ON COLUMN pick_note_lines.lot_number IS 'Numarul lotului de intrare din ERP (ex: ##E1000 POWERVINE 0-1012)';
COMMENT ON COLUMN pick_note_lines.quantity_remaining IS 'Cantitatea ramasa pe rola dupa taiere';
